version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your_app_key
      # - AMOCRM_CLIENT_ID=your_client_id
      # - AMOCRM_CLIENT_SECRET=your_client_secret
      # - AMOCRM_REDIRECT_URI=your_redirect_uri
      # - AMOCRM_DOMAIN=your_domain
